### ISSUE TITLE
[Tarea 1] Formato de entrega y cantidad de máquinas

### ISSUE THREAD

**Issue by lewebe** [IIC2213/Syllabus-2021-1-#1]
Hola, no me queda muy claro el formato de entrega de esta tarea. En el enunciado dice que se correrán dos tests para comprobar que mi máquina verifica que los strings son codificaciones de números naturales y otros dos para comprobar que el segundo número es sucesor del primero. Según lo que dijo el profesor en clases, yo solo hice una máquina que hiciera lo segundo (revisar que en un string _u#v_ , _v_ fuera sucesor de _u_). La revisión de que ambos strings son naturales está implicita en mi código, pues de otro modo no funcionaría, pero mi máquina no tiene estados de aceptación que no sean comprobar que el segundo número es sucesor del primero.

**Comment by Zetaku1** [comment]
Según lo que entiendo, la maquina es una sola y debería parar en el momento de que algún número no es codificación o ya cuando sabes que no son sucesores.

Por ejemplo un primer test podría ser 01#10, entonces la maquina debería parar cuando se da cuenta que el primer numero no es codificación.
Pero si le das 10#10 entonces la maquina debería seguir y empezar a verificar si es que el segundo numero es sucesor del primero.

**Comment by juanreutter** [comment]
Hola, complemento: no importa realmente como funciona la maquina, ni en que minuto para. Pero, si tiene que pasar que:
- rechaza el 001#10 ( por que u no es codificacion, ese seria un test del primer tipo)
- acepta el 11#100 pero rechaza el 11#101 (aca son codificaciones, pero uno tiene el sucesor, el otro no, esos son test del segundo tipo)
