### ISSUE TITLE
Ayudantía 1: problema 2 lenguajes rec enumerables ..

### ISSUE THREAD

**Issue by fprebolledo** [IIC2213/Syllabus-2021-1-#10]
Hola, no entiendo la parte de construir una nueva máquina que ignore cualquier input. Si ignora cualquier input significa que estará ejecutando C(M_2)0000w' todo el rato? no va a cambiar w' ni C(M_2) ? En el video M2 sería  la M que habíamos decidido antes?

**Comment by santilaguna** [comment]
Efectivamente, va a estar ejecutando C(M_2)0000w' todo el rato, pero nota que w' y M_2 son arbitrarias. El hecho de que sean arbitrarias implica que si pudiéramos construir M, entonces podrías resolver H.
