### ISSUE TITLE
[AY 1] Demostracion de indecidible

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213/Syllabus-2021-1-#12]
Hola, realmente no entendí la explicación del segundo video de la primera ayudantía, no me quedó claro como llegamos a que L(M1) = L1. Segun lo que entiendo ese paso es necesario para plantear M1 y seguir con la contradicción pero no me quedó claro en este ejemplo. (Además se habló de M, M1 y M2 entonces quizá tengo mezcladas qué significaba cada máquina? porque eso también me pareció confuso. Sé que M2 es arbitraria, pero entre M y M1 no entendí si se estaba refiriendo a la misma máquina o no)
edit: si M se refería a M1, entonces entiendo que por lo que se planteó al principio por contradiccion (L1 decidible), M1 tenía que plantearse de forma que se detuviera siempre, pero eso no estaba claro en la definición de M1, creo. No sé si esa es la gracia de la demostración, pero en general no me quedó claro el "paso a paso" del proceso.

**Comment by santilaguna** [comment]
Hola, M1 y M son distintas. Nosotros suponemos que M existe, luego dado que M existe nosotros podemos construir M1 como se muestra en el video

Luego, como tenemos M y L(M) = L1 (esto es lo que estamos suponiendo por definición de lenguaje decidible), podemos ingresar C(M1) como input.

Como sabemos que M para por nuestra suposición inicial, podemos determinar si M1 pertenece a L1 o no.

Luego, al saber si M1 pertenece a L1, podemos resolver el problema de la parada para M2 (por construcción de M1)

Si no se entiende alguna parte del proceso avísame, tienes razón de que faltó el paso a paso en el vídeo para que quedara más claro
