### ISSUE TITLE
[Tarea 2] Dudas sobre la parte A

### ISSUE THREAD

**Issue by BFFV** [IIC2213/Syllabus-2021-1-#13]
Hola, me surgieron un par de dudas con respecto a la tarea 2 y a las máquinas universales de Turing:

1) Si una máquina universal modificada ('M') contiene más de 1 sub-máquina en su interior, ¿la ejecución teórica de cada sub-máquina ocurre en paralelo, o en serie?. En otras palabras, si alguna de las máquinas en su interior se queda ejecutando **infinitamente**, ¿es posible ignorarla y llegar a la salida de la máquina universal usando la salida de las máquinas que **SÍ terminaron**?

2) En la condición de aceptación del lenguaje **MoM**, ¿el **'o'** entre ambas condiciones es inclusivo, o sólo se debe cumplir que exactamente 1 de las máquinas acepte a la codificación de la otra?

Saludos y gracias de antemano!

Edit: Al revisar las notas de la clase 3 vi que se pueden ejecutar las sub-máquinas en paralelo, alternando entre cada una, por lo que asumo que la respuesta a la primera pregunta es que sí es posible terminar la ejecución.

**Comment by juanreutter** [comment]
Hola, sobre: 
1. Tu sabes como funcionan las máquinas, tienen una cinta y ejecutan instrucciones. Si tienes que hacer dos sub-maquinas, me tienes que explicar como las vas a enlazar tu (lo que dices en el edit está OK). 
2. El o es inclusivo! Tienes un ejemplo de español donde se entienda que un o es exclusivo? me encantaría tenerlo para usarlo en la parte de lógica :)
