### ISSUE TITLE
[Tarea 2] Formalidad de la demostración

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2213/Syllabus-2021-1-#14]
Profesor, quería saber que tan formales debemos ser para la respuesta, por ejemplo si para alguna pregunta tengo que encontrar una máquina que represente un lenguaje, basta describirla y decir en mis palabra por qué funciona? O debe ser como nos hacían responder en teoría de autómatas, en que hay que mostrar que el lenguaje de la maquina, es subconjunto del lenguaje pedido y viceversa?

**Comment by juanreutter** [comment]
Vicente, hay dos cosas que son medio ortogonales. 
- Formalidad. En este curso todos los argumentos en el material escrito son bien formales, en clases obviamente no siempre se puede por que el español traiciona. 
- Nivel de abstracción. Entendiendo que las máquinas pueden hacer todo lo que podríamos hacer con un lenguaje de programación (al menos a nivel de funciones), lo que hacemos en este curso es aceptar un nivel de abstracción mucho mayor a la hora de específicar máquinas, simplemente decimos lo que hacen en vez de especificar como lo hacen. Pero sigue siendo formal!
