### ISSUE TITLE
[Tarea 2] Computabilidad

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2213/Syllabus-2021-1-#15]
Hola, para hacer una reducción de turing si encuentro mi función, debo decir por qué esta es computable? O la pueda asumir como tal?

**Comment by juanreutter** [comment]
Tienes que explicar por que es computable. Como cuando demostramos que un lenguaje es RE, la maquina de turing que muestra que la funcion es computable puede ser descrita a muy alto nivel
