### ISSUE TITLE
[Tarea 2] Reduccion

### ISSUE THREAD

**Issue by sameneses** [IIC2213/Syllabus-2021-1-#16]
Hola
No me queda claro que problemas conocidos podemos usar para reducir en la tarea ¿se puede usar cualquiera que hayamos visto?

Gracias

**Comment by juanreutter** [comment]
Casi: cualquiera que se haya demostrado que es indecidible. Pero ejercicios enunciados no-demostrados no puedes asumir que son indecidibles

**Comment by sameneses** [comment]
Entonces los que están en las notas de las clases con la solución son validos ¿correcto?
