### ISSUE TITLE
[Tarea 2] - Uso de instancia de DA

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2213/Syllabus-2021-1-#17]
Hola!

quería saber si es posible que en la tarea utilicemos una instancia del lenguaje DA visto en las notas de la semana 3, en particular, el caso en que a=Ɛ, sin la necesidad de demostrar que este es indecidible:

{w | existe una máquina M tal que w=C(M) y M acepta Ɛw=w}

Adjunto una captura del lenguaje DA
![image](https://user-images.githubusercontent.com/37163344/113194686-c58ada00-9237-11eb-8faa-8ac76fe4acb7.png)

Saludos :)

**Comment by juanreutter** [comment]
Si, niun problema

**Comment by juanreutter** [comment]
En general: cualquier cosa que se demuestre indecidible en clases o en las notas, vale! DA está demostrado en un video

**Comment by VicenteVicente** [comment]
Genial, muchas gracias por responder tan rápido profesor 😄

**Comment by VicenteMerino** [comment]
Igual creo que ese 'aw' es un typo y falta un espacio y debería decir 'acepta a w', no se si lo podría confirmar @juanreutter ?

**Comment by juanreutter** [comment]
confirmado
