### ISSUE TITLE
Template LaTeX

### ISSUE THREAD

**Issue by ignacio-urrutia** [IIC2213/Syllabus-2021-1-#19]
Estimado profesor, solo para preguntar si subió finalmente el template de LaTeX que nos ofreció para utilizar en la tarea porque no lo encontré en el repositorio En caso contrario, tome esta issue como un recordatorio amigable. 

Saludos

**Comment by ricardor4** [comment]
No es necesario usar un template en particular, sirve cualquiera, incluso alguno que salga en internet.
 El código de abajo es suficiente



```
\documentclass{article}
    % formato documento
    \usepackage[margin=0.7in]{geometry}
    \usepackage[parfill]{parskip}
    \usepackage[utf8]{inputenc}
    \usepackage[spanish]{babel}
    % para escribir matemáticas
    \usepackage{amsmath,amssymb,amsfonts,amsthm}

\begin{document}

Nombre, Fecha, Tarea X

\section*{Parte a}

Respuesta

\section*{Parte b}

etc

\end{document}
```

**Comment by juanreutter** [comment]
Gracias por el recordatorio! Les dejé el código fuente de la semana 3 en la carpeta de Tareas. Este tex tiene algunos de los macros que están usando, con eso pueden borrar, copiar/pegar, etc.

**Comment by DiegoEmilio01** [comment]
Hola, yo escribo mis tareas en este formato para evitar cansancio en los ojos. Me preguntaba si les gustaría que las subiera así (dark mode). En caso de que se pueda, puedo dejar el código que lo reproduce.

<img src="https://user-images.githubusercontent.com/48391930/113490144-ae015a80-949e-11eb-9b6a-18b86eae00d3.png" height=450px>

**Comment by cjdelacuadra** [comment]
aqui dejo un template que me dieron en otro curso por si alguien prefiere, tiene varios paquetes ya incluidos.
para importar imagenes recomiendo usar 
\includegraphics[width=2cm]{img/--------}
e importar las imagenes dentro de una carpeta (yo la uso con nombre img)
--------------------------------------------------
\documentclass[12pt]{article}

% Margen de 1 pulgada por lado
\usepackage{fullpage}
% Incluye gráficas
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage[none]{hyphenat}
\usepackage{parskip}
\usepackage[spanish]{babel}
\usepackage[utf8]{inputenc}
\usepackage{hyperref}
\usepackage{fancyhdr}
\setlength{\headheight}{15.2pt}
\setlength{\headsep}{5pt}
\pagestyle{fancy}

\newcommand{\N}{\mathbb{N}}
\newcommand{\Exp}[1]{\mathcal{E}_{#1}}
\newcommand{\List}[1]{\mathcal{L}_{#1}}
\newcommand{\EN}{\Exp{\N}}
\newcommand{\LN}{\List{\N}}

\newcommand{\comment}[1]{}
\newcommand{\lb}{\\~\\}
\newcommand{\eop}{_{\square}}
\newcommand{\hsig}{\hat{\sigma}}
\newcommand{\ra}{\rightarrow}
\newcommand{\lra}{\leftrightarrow}

\newcommand{\alumno}{nombre - N alumno}
\rhead{Tarea 2 - \alumno}

\begin{document}
\thispagestyle{empty}

\begin{minipage}{2.3cm}
\includegraphics[width=2cm]{img/logo.pdf}
\vspace{0.5cm} % Altura de la corona del logo, así el texto queda alineado verticalmente con el círculo del logo.
\end{minipage}
\begin{minipage}{\linewidth}
\textsc{\raggedright \footnotesize
Pontificia Universidad Católica de Chile \\
Departamento de Ciencia de la Computación \\
IIC2213 - Sección 1 - Lógica para Ciencias de la Computación \\}
\end{minipage}


% Titulo
\begin{center}
\vspace{0.5cm}
{\huge\bf Tarea 2}\\
\vspace{0.2cm}
\today\\
\vspace{0.2cm}
\footnotesize{1º semestre 2021 - Juan Reutter}\\
\vspace{0.2cm}
\footnotesize{\alumno}
\rule{\textwidth}{0.05mm}
\end{center}



\section*{Respuestas}
% Estas numeracion es solo de ejemplo

\subsection*{Pregunta 1}
\subsubsection*{Pregunta 1.1}
% Respuesta pregunta
\subsubsection*{Pregunta 1.2}
% Respuesta pregunta

\newpage
\subsection*{Pregunta 2}

\subsubsection*{Pregunta 2.1}
% Respuesta pregunta
\subsubsection*{Pregunta 2.2}
% Respuesta pregunta

% Fin del documento
\end{document}

**Comment by juanreutter** [comment]
Cualquier template esta bien! Incluido el negro, que me encantaria ver como se hace

**Comment by DiegoEmilio01** [comment]
Gracias! Utilizo el paquete "xcolor" para ello. El código que utilizo es el que dejo en este comentario. Con él me queda disponible el comando `\invert` que "invierte" los colores de la página y de las letras (también tengo el logo de la U invertido para otros contextos jaja). Así, edito el doc con el comando activado y si me lo piden con el formato tradicional (fome) lo compilo sin el comando antes de entregar.   
```latex
\usepackage{xcolor}
\newcommand{\backgroundcol}{\pagecolor[RGB]{51,51,51}}
\newcommand{\textcol}{\color{white}}
\newcommand{\invert}{\backgroundcol\textcol}
```
