### ISSUE TITLE
[Tarea 1] Duda sobre escritura en la cinta

### ISSUE THREAD

**Issue by lucasvsj** [IIC2213/Syllabus-2021-1-#2]
Hola buenas
¿Es posible escribir algún carácter que **no** pertenezca al alfabeto entregado en el enunciado en la cinta de la máquina?
Por ejemplo, ¿es factible escribir la letra "A" en la cinta?
De antemano muchas gracias

**Comment by juanreutter** [comment]
Hola, solo el blanco (ese simbolo adicional que tienen las maquinas, con el que parte toda la cinta que no tiene el input)

**Comment by lewebe** [comment]
Entonces no podemos usar ningún simbolo que no sea {0,1,#,_} ?

**Comment by StroveLight** [comment]
Entonces no podemos hacer cosas que hace el ejemplo de "Duplicate binary string", que escribe "i" y "o", pese a solo recibir 0s y 1s?

**Comment by juanreutter** [comment]
El problema es que, según las definiciones que vimos en clases, las máquinas funcionan con un alfabeto dado, y tienen que hacer cosas con cualquier string de ese alfabeto. Entonces si tu máquina tiene i, o disponibles debería funcionar con alfabeto {1,0,#,i,o}, pero eso no es lo que se pide en la tarea. 

Ahora bien, siendo honestos, no tenemos forma de verificar esto, la nota depende de cuatro tests. Supongo que si tienes la mala suerte que justo nos fijemos en las cosas que escribe la máquina, tendríamos que bajar puntaje...
