### ISSUE TITLE
[Tarea 2] Pregunta Enunciado

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2213/Syllabus-2021-1-#21]
Hola!

Cuando nos mencionan en el enunciado que la máquina M₁ acepta C(M₂) se refiere a que (1) dicha máquina acepta ese lenguaje y procede a funcionar o se refiere a que (2) M₁ se **detiene** con C(M₂) y "acepta" ese input.

Muchas gracias.

**Comment by juanreutter** [comment]
Lo segubdo: la maquina M1 se detiene en un estado final cuando le damos como input el string C(M2)
