### ISSUE TITLE
[Tarea 2] Teorema de Reducción para lenguajes Recursivamente Numerables

### ISSUE THREAD

**Issue by lothardp** [IIC2213/Syllabus-2021-1-#22]
Hola! 
¿Sirve el teorema de la reducción para lenguajes Recursivamente Numerables? Me refiero a si tengo una reducción f computable de L1 a L2, se cumple lo siguiente?
- si L2 es RN entonces L1 es RN,
- y si L1 no es RN, entonces L2 no es RN.

Gracias!

**Comment by juanreutter** [comment]
Que buena pregunta! Mira, trata primero de reproducir la demostración de esto que me dices, punto numero 1 (L2 es RN entonces L1 es RN) pero ahora pensando en que la máquina para L2 puede no detenerse. Cambia algo en la demostración?

**Comment by lothardp** [comment]
Le di un poco de vueltas y según yo la demostración sigue siendo válida, creo que no depende en que M2 pare o no, por lo que si L1 es reducible a L2 y L2 es RE, entonces L1 también es RE. ¿es así o se me está pasando algo?

pd. me di cuenta recien que le estaba diciendo RN y es RE jajaaj
