### ISSUE TITLE
[Tarea 2] Plazo y Calendario Académico

### ISSUE THREAD

**Issue by mistico0121** [IIC2213/Syllabus-2021-1-#23]
Hola

Tengo una duda. En el calendario académico https://admisionyregistros.uc.cl/images/pdf/calendarioUC/calendario_academico_2021.pdf aparece que no puede haber evaluaciones dentro de los días 5-7 de Abril. Esto afecta el plazo de la Tarea 2?

Saludos

**Comment by juanreutter** [comment]
Hola, no, eso tiene que ver con evaluaciones o controles en ese día, no en tareas que se entregan antes. De todas formas, la invitación siempre es que problemas puntuales los veamos por interno.

**Comment by modprob-puc** [comment]
Hola rofe en el correo que mandoó recién dice: "*recuerden la **tarea 3**. Voy a dejar el buzón abierto **hasta mañana am**. "

¿Se refiere a la Tarea 2? ¿y hasta que hora queda el plazo de ser así?

gracias
