### ISSUE TITLE
[Tarea 1] Verificación "implícita" de ser codificación binaria

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213/Syllabus-2021-1-#4]
Hola! Leyendo el enunciado me surgió una duda sobre el primer par de tests. Sale que estos son "para revisar que los strings son codificaciones". 
Me pasa que tengo un código que, hasta lo que sé, funciona bien verificando si, dado n#m, m es sucesor de n. Pero no revisa "explícitamente" que estos dos strings sean codificaciones. Sí lo hace de forma implícita junto al resto del proceso (no sé cómo explicarlo mejor sin decir nada sobre el código).
Dado estos tests, funcionaría con mi código?

Y una pregunta extra, se puede actualizar una entrega en el siding? Si subo algo y de ahí lo corrijo, se puede subir de nuevo? (pregunto por si acaso)

EDIT: Leí otro issue parecido al mío y me quedó más claro, pero mantengo la segunda pregunta. :)

**Comment by juanreutter** [comment]
Si tu codigo rechaza strings del estilo 01#10 y 1# 010 (sin el espacio entremedio, es que no me escribe bien) , todo bien (esos no son los tests pero son de ese estilo - es para que al menos tengas un 4 en la tarea solo haciendo la parte de verificar strings). 

Se puede mandar todas las veces que quieras al siding.

**Comment by sopadeoliva** [comment]
Gracias! No me quedó claro por qué debería rechazar el string 1#10?

**Comment by juanreutter** [comment]
Ahi lo edite. Resulta que markdown se come el cero si lo pongo junto: por alguna razon me transforma el 1# 010 (sin espacio) en 1#10.

**Comment by sopadeoliva** [comment]
aaaaah, ok jajajjaa gracias
