### ISSUE TITLE
[Tarea 1] Cambiar la cinta

### ISSUE THREAD

**Issue by Gjescalante** [IIC2213/Syllabus-2021-1-#6]
Hola! quería asegurarme de si es válido cambiar los elementos de la cinta mientras se está recorriendo, al final lo único que importa es que acepte o rechace en los casos mencionados en el enunciado, ¿no? Gracias por su tiempo.

**Comment by juanreutter** [comment]
Siempre puedes escribir otros simbolos del alfabeto {0,1,#} o blancos. Simbolos adicionales no es la idea (aunque no tengo como verificarlo automaticamente, mira el #2 )
