### ISSUE TITLE
[Tarea 1] Verificación más de un #

### ISSUE THREAD

**Issue by danielauu** [IIC2213/Syllabus-2021-1-#7]
Hola, quería saber si en la tarea es necesario que nuestra máquina rechace palabras del tipo 1101#1#100. Es decir, que tengan más de un gato en la palabra.
Gracias de antemano!

**Comment by juanreutter** [comment]
Hola, si es necesario, no vamos a hacer tests para eso

**Comment by Okhan97** [comment]
> Hola, si es necesario, no vamos a hacer tests para eso

No entiendo profe, si pasamos los test pero no chequeamos ese caso en especifico ¿entonces que ocurre con el puntaje?

**Comment by juanreutter** [comment]
Un 7 po. Pero si no hacen ese caso van a tener que vivir para siempre sabiendo que no terminaron su maquina :)
