### ISSUE TITLE
[Tarea 1] Más de 1 cinta

### ISSUE THREAD

**Issue by mistico0121** [IIC2213/Syllabus-2021-1-#8]
Hola

Quería saber si mi máquina podía tener más de 1 cinta, pues eso me facilita varias operaciones por el hecho de poder ir copiando o sumando o comparando los numeros binarios(lo hice parecido a los ejemplos en el sitio), pero no es algo que esté especificado en el enunciado y me genera dudas si puedo hacerlo o no.

De antemano, muchas gracias.

**Comment by juanreutter** [comment]
Hola, no, no puede usar mas de una cinta (es que con dos sale directo de los otros ejemplos). No esta en el enunciado por que la definicion que vimos en el curso solo contempla una cinta.

**Comment by CristobalHV** [comment]
hola!

vi esta issue recién y dado que en los ejemplos de https://turingmachinesimulator.com/ se utilizaba más de una cinta y no se mencionaba nada de esto en el enunciado, asumí erróneamente que si se podía usar más de una cinta para esta tarea.

No alcanzo a corregir esto en el tiempo que queda para la entrega (~30 minutos), ¿sería posible entregar la tarea corregida con una cinta durante el fin de semana?

Gracias de antemano

**Comment by juanreutter** [comment]
Dale. Mandame un correo con el codigo el fin de semana
