### ISSUE TITLE
Ayudantía 1: lenguajes recursivamente enumerables y decidibles

### ISSUE THREAD

**Issue by fprebolledo** [IIC2213/Syllabus-2021-1-#9]
Tengo una duda, en el primer [ejercicio ](https://drive.google.com/file/d/1ocqbWbiRLZYAAtMMxx4-vtId6226EZ2S/view)de lenguajes recursivamente enumerables y decidibles. Para construir M se da una serie de pasos, pero nunca se construye M, ni se verifica nada. Si me sale algo parecido en una tarea se puede hacer esto? o debo construir M? Si la debo construir creo que en la ayudantía se debería haber mostrado este proceso, porque no me queda muy claro.

**Comment by juanreutter** [comment]
No, no hay que construirla! (imagínate, estaríamos todo el semestre en eso...). 
Si alguna vez les pido construir la máquina a nivel de estados y transiciones, se los voy a detallar específicamente. Pero lo que está en el video basta y sobra para demostrar que un lenguaje es RE o que es decidible
